# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('gb_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gb_id', models.CharField(blank=True, max_length=10, null=True)),
                ('gb_character', models.CharField(choices=[('deeja', 'Deeja'), ('gran', 'Gran')], default='deeja', max_length=20)),
                ('gb_class', models.CharField(choices=[('fighter', 'Fighter'), ('berserker', 'Berserker'), ('spartan', 'Spartan'), ('sage', 'Sage'), ('warlock', 'Warlock'), ('bandit_tyloon', 'Bandit Tyloon'), ('chaos_ruler', 'Chaos Ruler'), ('luchador', 'Luchador'), ('nighthound', 'Nighthound'), ('elysian', 'Elysian'), ('apsaras', 'Apsaras')], default='fighter', max_length=20)),
                ('gb_waifu', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('discord', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
            ],
        ),
    ]
